"""initial schema

Revision ID: f4fd2f814c46
Revises: 
Create Date: 2026-01-20 13:09:39.763060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4fd2f814c46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canada_wage_2012_2025',
    sa.Column('noc_cnp', sa.String(length=10), nullable=True),
    sa.Column('noc_title_eng', sa.String(length=255), nullable=True),
    sa.Column('noc_title_fra', sa.String(length=255), nullable=True),
    sa.Column('prov', sa.String(length=10), nullable=True),
    sa.Column('er_code_code_re', sa.String(length=20), nullable=True),
    sa.Column('er_name', sa.String(length=255), nullable=True),
    sa.Column('nom_re', sa.String(length=255), nullable=True),
    sa.Column('low_wage_salaire_minium', sa.Integer(), nullable=True),
    sa.Column('median_wage_salaire_median', sa.Integer(), nullable=True),
    sa.Column('high_wage_salaire_maximal', sa.Integer(), nullable=True),
    sa.Column('average_wage_salaire_moyen', sa.Integer(), nullable=True),
    sa.Column('quartile1_wage_salaire_quartile1', sa.Integer(), nullable=True),
    sa.Column('quartile3_wage_salaire_quartile3', sa.Integer(), nullable=True),
    sa.Column('annual_wage_flag_salaire_annuel', sa.Boolean(), nullable=False),
    sa.Column('source2025_nhq', sa.String(length=255), nullable=True),
    sa.Column('data_source_e', sa.String(length=255), nullable=True),
    sa.Column('data_source_f', sa.String(length=255), nullable=True),
    sa.Column('reference_period', sa.String(length=20), nullable=True),
    sa.Column('revision_date_date_revision', sa.Date(), nullable=True),
    sa.Column('wage_comment_e', sa.Text(), nullable=True),
    sa.Column('wage_comment_f', sa.Text(), nullable=True),
    sa.Column('employeeswithnonwagebenefit_pct', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wages_er_code_code_re', 'canada_wage_2012_2025', ['er_code_code_re'], unique=False)
    op.create_index('idx_wages_noc_cnp', 'canada_wage_2012_2025', ['noc_cnp'], unique=False)
    op.create_index('idx_wages_noc_prov', 'canada_wage_2012_2025', ['noc_cnp', 'prov'], unique=False)
    op.create_index('idx_wages_prov', 'canada_wage_2012_2025', ['prov'], unique=False)
    op.create_index('idx_wages_reference_period', 'canada_wage_2012_2025', ['reference_period'], unique=False)
    op.create_index(op.f('ix_canada_wage_2012_2025_classification'), 'canada_wage_2012_2025', ['classification'], unique=False)
    op.create_index(op.f('ix_canada_wage_2012_2025_id'), 'canada_wage_2012_2025', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canada_wage_2012_2025_id'), table_name='canada_wage_2012_2025')
    op.drop_index(op.f('ix_canada_wage_2012_2025_classification'), table_name='canada_wage_2012_2025')
    op.drop_index('idx_wages_reference_period', table_name='canada_wage_2012_2025')
    op.drop_index('idx_wages_prov', table_name='canada_wage_2012_2025')
    op.drop_index('idx_wages_noc_prov', table_name='canada_wage_2012_2025')
    op.drop_index('idx_wages_noc_cnp', table_name='canada_wage_2012_2025')
    op.drop_index('idx_wages_er_code_code_re', table_name='canada_wage_2012_2025')
    op.drop_table('canada_wage_2012_2025')
    # ### end Alembic commands ###
